// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * DatadogMetric allows autoscaling on arbitrary Datadog query
 *
 * @schema DatadogMetric
 */
export class DatadogMetric extends ApiObject {
  /**
   * Returns the apiVersion and kind for "DatadogMetric"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'datadoghq.com/v1alpha1',
    kind: 'DatadogMetric',
  }

  /**
   * Renders a Kubernetes manifest for "DatadogMetric".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: DatadogMetricProps = {}): any {
    return {
      ...DatadogMetric.GVK,
      ...toJson_DatadogMetricProps(props),
    };
  }

  /**
   * Defines a "DatadogMetric" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: DatadogMetricProps = {}) {
    super(scope, id, {
      ...DatadogMetric.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...DatadogMetric.GVK,
      ...toJson_DatadogMetricProps(resolved),
    };
  }
}

/**
 * DatadogMetric allows autoscaling on arbitrary Datadog query
 *
 * @schema DatadogMetric
 */
export interface DatadogMetricProps {
  /**
   * @schema DatadogMetric#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * DatadogMetricSpec defines the desired state of DatadogMetric
   *
   * @schema DatadogMetric#spec
   */
  readonly spec?: DatadogMetricSpec;

}

/**
 * Converts an object of type 'DatadogMetricProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DatadogMetricProps(obj: DatadogMetricProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_DatadogMetricSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * DatadogMetricSpec defines the desired state of DatadogMetric
 *
 * @schema DatadogMetricSpec
 */
export interface DatadogMetricSpec {
  /**
   * ExternalMetricName is reserved for internal use
   *
   * @schema DatadogMetricSpec#externalMetricName
   */
  readonly externalMetricName?: string;

  /**
   * MaxAge provides the max age for the metric query (overrides the default setting `external_metrics_provider.max_age`)
   *
   * @schema DatadogMetricSpec#maxAge
   */
  readonly maxAge?: string;

  /**
   * Query is the raw datadog query
   *
   * @schema DatadogMetricSpec#query
   */
  readonly query?: string;

  /**
   * TimeWindow provides the time window for the metric query, defaults to MaxAge.
   *
   * @schema DatadogMetricSpec#timeWindow
   */
  readonly timeWindow?: string;

}

/**
 * Converts an object of type 'DatadogMetricSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DatadogMetricSpec(obj: DatadogMetricSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'externalMetricName': obj.externalMetricName,
    'maxAge': obj.maxAge,
    'query': obj.query,
    'timeWindow': obj.timeWindow,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

