// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema ServiceProfile
 */
export class ServiceProfile extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ServiceProfile"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'linkerd.io/v1alpha1',
    kind: 'ServiceProfile',
  }

  /**
   * Renders a Kubernetes manifest for "ServiceProfile".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ServiceProfileProps = {}): any {
    return {
      ...ServiceProfile.GVK,
      ...toJson_ServiceProfileProps(props),
    };
  }

  /**
   * Defines a "ServiceProfile" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ServiceProfileProps = {}) {
    super(scope, id, {
      ...ServiceProfile.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...ServiceProfile.GVK,
      ...toJson_ServiceProfileProps(resolved),
    };
  }
}

/**
 * @schema ServiceProfile
 */
export interface ServiceProfileProps {
  /**
   * @schema ServiceProfile#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Spec is the custom resource spec
   *
   * @schema ServiceProfile#spec
   */
  readonly spec?: ServiceProfileSpec;

}

/**
 * Converts an object of type 'ServiceProfileProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileProps(obj: ServiceProfileProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ServiceProfileSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Spec is the custom resource spec
 *
 * @schema ServiceProfileSpec
 */
export interface ServiceProfileSpec {
  /**
   * @schema ServiceProfileSpec#dstOverrides
   */
  readonly dstOverrides?: ServiceProfileSpecDstOverrides[];

  /**
   * @schema ServiceProfileSpec#opaquePorts
   */
  readonly opaquePorts?: string[];

  /**
   * RetryBudget describes the maximum number of retries that should be issued to this service.
   *
   * @schema ServiceProfileSpec#retryBudget
   */
  readonly retryBudget?: ServiceProfileSpecRetryBudget;

  /**
   * @schema ServiceProfileSpec#routes
   */
  readonly routes: ServiceProfileSpecRoutes[];

}

/**
 * Converts an object of type 'ServiceProfileSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpec(obj: ServiceProfileSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'dstOverrides': obj.dstOverrides?.map(y => toJson_ServiceProfileSpecDstOverrides(y)),
    'opaquePorts': obj.opaquePorts?.map(y => y),
    'retryBudget': toJson_ServiceProfileSpecRetryBudget(obj.retryBudget),
    'routes': obj.routes?.map(y => toJson_ServiceProfileSpecRoutes(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * WeightedDst is a weighted alternate destination.
 *
 * @schema ServiceProfileSpecDstOverrides
 */
export interface ServiceProfileSpecDstOverrides {
  /**
   * @schema ServiceProfileSpecDstOverrides#authority
   */
  readonly authority?: string;

  /**
   * @schema ServiceProfileSpecDstOverrides#weight
   */
  readonly weight?: ServiceProfileSpecDstOverridesWeight;

}

/**
 * Converts an object of type 'ServiceProfileSpecDstOverrides' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecDstOverrides(obj: ServiceProfileSpecDstOverrides | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'authority': obj.authority,
    'weight': obj.weight?.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * RetryBudget describes the maximum number of retries that should be issued to this service.
 *
 * @schema ServiceProfileSpecRetryBudget
 */
export interface ServiceProfileSpecRetryBudget {
  /**
   * @schema ServiceProfileSpecRetryBudget#minRetriesPerSecond
   */
  readonly minRetriesPerSecond: number;

  /**
   * @schema ServiceProfileSpecRetryBudget#retryRatio
   */
  readonly retryRatio: number;

  /**
   * @schema ServiceProfileSpecRetryBudget#ttl
   */
  readonly ttl: string;

}

/**
 * Converts an object of type 'ServiceProfileSpecRetryBudget' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRetryBudget(obj: ServiceProfileSpecRetryBudget | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'minRetriesPerSecond': obj.minRetriesPerSecond,
    'retryRatio': obj.retryRatio,
    'ttl': obj.ttl,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * RouteSpec specifies a Route resource.
 *
 * @schema ServiceProfileSpecRoutes
 */
export interface ServiceProfileSpecRoutes {
  /**
   * RequestMatch describes the conditions under which to match a Route.
   *
   * @schema ServiceProfileSpecRoutes#condition
   */
  readonly condition: ServiceProfileSpecRoutesCondition;

  /**
   * @schema ServiceProfileSpecRoutes#isRetryable
   */
  readonly isRetryable?: boolean;

  /**
   * @schema ServiceProfileSpecRoutes#name
   */
  readonly name: string;

  /**
   * @schema ServiceProfileSpecRoutes#responseClasses
   */
  readonly responseClasses?: ServiceProfileSpecRoutesResponseClasses[];

  /**
   * @schema ServiceProfileSpecRoutes#timeout
   */
  readonly timeout?: string;

}

/**
 * Converts an object of type 'ServiceProfileSpecRoutes' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRoutes(obj: ServiceProfileSpecRoutes | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'condition': toJson_ServiceProfileSpecRoutesCondition(obj.condition),
    'isRetryable': obj.isRetryable,
    'name': obj.name,
    'responseClasses': obj.responseClasses?.map(y => toJson_ServiceProfileSpecRoutesResponseClasses(y)),
    'timeout': obj.timeout,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ServiceProfileSpecDstOverridesWeight
 */
export class ServiceProfileSpecDstOverridesWeight {
  public static fromNumber(value: number): ServiceProfileSpecDstOverridesWeight {
    return new ServiceProfileSpecDstOverridesWeight(value);
  }
  public static fromString(value: string): ServiceProfileSpecDstOverridesWeight {
    return new ServiceProfileSpecDstOverridesWeight(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * RequestMatch describes the conditions under which to match a Route.
 *
 * @schema ServiceProfileSpecRoutesCondition
 */
export interface ServiceProfileSpecRoutesCondition {
  /**
   * @schema ServiceProfileSpecRoutesCondition#all
   */
  readonly all?: any[];

  /**
   * @schema ServiceProfileSpecRoutesCondition#any
   */
  readonly any?: any[];

  /**
   * @schema ServiceProfileSpecRoutesCondition#method
   */
  readonly method?: string;

  /**
   * @schema ServiceProfileSpecRoutesCondition#not
   */
  readonly not?: any[];

  /**
   * @schema ServiceProfileSpecRoutesCondition#pathRegex
   */
  readonly pathRegex?: string;

}

/**
 * Converts an object of type 'ServiceProfileSpecRoutesCondition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRoutesCondition(obj: ServiceProfileSpecRoutesCondition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'all': obj.all?.map(y => y),
    'any': obj.any?.map(y => y),
    'method': obj.method,
    'not': obj.not?.map(y => y),
    'pathRegex': obj.pathRegex,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ResponseClass describes how to classify a response (e.g. success or failures).
 *
 * @schema ServiceProfileSpecRoutesResponseClasses
 */
export interface ServiceProfileSpecRoutesResponseClasses {
  /**
   * ResponseMatch describes the conditions under which to classify a response.
   *
   * @schema ServiceProfileSpecRoutesResponseClasses#condition
   */
  readonly condition: ServiceProfileSpecRoutesResponseClassesCondition;

  /**
   * @schema ServiceProfileSpecRoutesResponseClasses#isFailure
   */
  readonly isFailure?: boolean;

}

/**
 * Converts an object of type 'ServiceProfileSpecRoutesResponseClasses' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRoutesResponseClasses(obj: ServiceProfileSpecRoutesResponseClasses | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'condition': toJson_ServiceProfileSpecRoutesResponseClassesCondition(obj.condition),
    'isFailure': obj.isFailure,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ResponseMatch describes the conditions under which to classify a response.
 *
 * @schema ServiceProfileSpecRoutesResponseClassesCondition
 */
export interface ServiceProfileSpecRoutesResponseClassesCondition {
  /**
   * @schema ServiceProfileSpecRoutesResponseClassesCondition#all
   */
  readonly all?: any[];

  /**
   * @schema ServiceProfileSpecRoutesResponseClassesCondition#any
   */
  readonly any?: any[];

  /**
   * @schema ServiceProfileSpecRoutesResponseClassesCondition#not
   */
  readonly not?: any[];

  /**
   * Range describes a range of integers (e.g. status codes).
   *
   * @schema ServiceProfileSpecRoutesResponseClassesCondition#status
   */
  readonly status?: ServiceProfileSpecRoutesResponseClassesConditionStatus;

}

/**
 * Converts an object of type 'ServiceProfileSpecRoutesResponseClassesCondition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRoutesResponseClassesCondition(obj: ServiceProfileSpecRoutesResponseClassesCondition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'all': obj.all?.map(y => y),
    'any': obj.any?.map(y => y),
    'not': obj.not?.map(y => y),
    'status': toJson_ServiceProfileSpecRoutesResponseClassesConditionStatus(obj.status),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Range describes a range of integers (e.g. status codes).
 *
 * @schema ServiceProfileSpecRoutesResponseClassesConditionStatus
 */
export interface ServiceProfileSpecRoutesResponseClassesConditionStatus {
  /**
   * @schema ServiceProfileSpecRoutesResponseClassesConditionStatus#max
   */
  readonly max?: number;

  /**
   * @schema ServiceProfileSpecRoutesResponseClassesConditionStatus#min
   */
  readonly min?: number;

}

/**
 * Converts an object of type 'ServiceProfileSpecRoutesResponseClassesConditionStatus' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileSpecRoutesResponseClassesConditionStatus(obj: ServiceProfileSpecRoutesResponseClassesConditionStatus | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'max': obj.max,
    'min': obj.min,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema ServiceProfileV1Alpha2
 */
export class ServiceProfileV1Alpha2 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ServiceProfileV1Alpha2"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'linkerd.io/v1alpha2',
    kind: 'ServiceProfile',
  }

  /**
   * Renders a Kubernetes manifest for "ServiceProfileV1Alpha2".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ServiceProfileV1Alpha2Props = {}): any {
    return {
      ...ServiceProfileV1Alpha2.GVK,
      ...toJson_ServiceProfileV1Alpha2Props(props),
    };
  }

  /**
   * Defines a "ServiceProfileV1Alpha2" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ServiceProfileV1Alpha2Props = {}) {
    super(scope, id, {
      ...ServiceProfileV1Alpha2.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...ServiceProfileV1Alpha2.GVK,
      ...toJson_ServiceProfileV1Alpha2Props(resolved),
    };
  }
}

/**
 * @schema ServiceProfileV1Alpha2
 */
export interface ServiceProfileV1Alpha2Props {
  /**
   * @schema ServiceProfileV1Alpha2#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Spec is the custom resource spec
   *
   * @schema ServiceProfileV1Alpha2#spec
   */
  readonly spec?: ServiceProfileV1Alpha2Spec;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2Props' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2Props(obj: ServiceProfileV1Alpha2Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ServiceProfileV1Alpha2Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Spec is the custom resource spec
 *
 * @schema ServiceProfileV1Alpha2Spec
 */
export interface ServiceProfileV1Alpha2Spec {
  /**
   * @schema ServiceProfileV1Alpha2Spec#dstOverrides
   */
  readonly dstOverrides?: ServiceProfileV1Alpha2SpecDstOverrides[];

  /**
   * @schema ServiceProfileV1Alpha2Spec#opaquePorts
   */
  readonly opaquePorts?: string[];

  /**
   * RetryBudget describes the maximum number of retries that should be issued to this service.
   *
   * @schema ServiceProfileV1Alpha2Spec#retryBudget
   */
  readonly retryBudget?: ServiceProfileV1Alpha2SpecRetryBudget;

  /**
   * @schema ServiceProfileV1Alpha2Spec#routes
   */
  readonly routes?: ServiceProfileV1Alpha2SpecRoutes[];

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2Spec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2Spec(obj: ServiceProfileV1Alpha2Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'dstOverrides': obj.dstOverrides?.map(y => toJson_ServiceProfileV1Alpha2SpecDstOverrides(y)),
    'opaquePorts': obj.opaquePorts?.map(y => y),
    'retryBudget': toJson_ServiceProfileV1Alpha2SpecRetryBudget(obj.retryBudget),
    'routes': obj.routes?.map(y => toJson_ServiceProfileV1Alpha2SpecRoutes(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * WeightedDst is a weighted alternate destination.
 *
 * @schema ServiceProfileV1Alpha2SpecDstOverrides
 */
export interface ServiceProfileV1Alpha2SpecDstOverrides {
  /**
   * @schema ServiceProfileV1Alpha2SpecDstOverrides#authority
   */
  readonly authority?: string;

  /**
   * @schema ServiceProfileV1Alpha2SpecDstOverrides#weight
   */
  readonly weight?: ServiceProfileV1Alpha2SpecDstOverridesWeight;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecDstOverrides' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecDstOverrides(obj: ServiceProfileV1Alpha2SpecDstOverrides | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'authority': obj.authority,
    'weight': obj.weight?.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * RetryBudget describes the maximum number of retries that should be issued to this service.
 *
 * @schema ServiceProfileV1Alpha2SpecRetryBudget
 */
export interface ServiceProfileV1Alpha2SpecRetryBudget {
  /**
   * @schema ServiceProfileV1Alpha2SpecRetryBudget#minRetriesPerSecond
   */
  readonly minRetriesPerSecond: number;

  /**
   * @schema ServiceProfileV1Alpha2SpecRetryBudget#retryRatio
   */
  readonly retryRatio: number;

  /**
   * @schema ServiceProfileV1Alpha2SpecRetryBudget#ttl
   */
  readonly ttl: string;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRetryBudget' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRetryBudget(obj: ServiceProfileV1Alpha2SpecRetryBudget | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'minRetriesPerSecond': obj.minRetriesPerSecond,
    'retryRatio': obj.retryRatio,
    'ttl': obj.ttl,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * RouteSpec specifies a Route resource.
 *
 * @schema ServiceProfileV1Alpha2SpecRoutes
 */
export interface ServiceProfileV1Alpha2SpecRoutes {
  /**
   * RequestMatch describes the conditions under which to match a Route.
   *
   * @schema ServiceProfileV1Alpha2SpecRoutes#condition
   */
  readonly condition: ServiceProfileV1Alpha2SpecRoutesCondition;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutes#isRetryable
   */
  readonly isRetryable?: boolean;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutes#name
   */
  readonly name: string;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutes#responseClasses
   */
  readonly responseClasses?: ServiceProfileV1Alpha2SpecRoutesResponseClasses[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutes#timeout
   */
  readonly timeout?: string;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRoutes' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRoutes(obj: ServiceProfileV1Alpha2SpecRoutes | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'condition': toJson_ServiceProfileV1Alpha2SpecRoutesCondition(obj.condition),
    'isRetryable': obj.isRetryable,
    'name': obj.name,
    'responseClasses': obj.responseClasses?.map(y => toJson_ServiceProfileV1Alpha2SpecRoutesResponseClasses(y)),
    'timeout': obj.timeout,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ServiceProfileV1Alpha2SpecDstOverridesWeight
 */
export class ServiceProfileV1Alpha2SpecDstOverridesWeight {
  public static fromNumber(value: number): ServiceProfileV1Alpha2SpecDstOverridesWeight {
    return new ServiceProfileV1Alpha2SpecDstOverridesWeight(value);
  }
  public static fromString(value: string): ServiceProfileV1Alpha2SpecDstOverridesWeight {
    return new ServiceProfileV1Alpha2SpecDstOverridesWeight(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * RequestMatch describes the conditions under which to match a Route.
 *
 * @schema ServiceProfileV1Alpha2SpecRoutesCondition
 */
export interface ServiceProfileV1Alpha2SpecRoutesCondition {
  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesCondition#all
   */
  readonly all?: any[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesCondition#any
   */
  readonly any?: any[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesCondition#method
   */
  readonly method?: string;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesCondition#not
   */
  readonly not?: any[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesCondition#pathRegex
   */
  readonly pathRegex?: string;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRoutesCondition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRoutesCondition(obj: ServiceProfileV1Alpha2SpecRoutesCondition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'all': obj.all?.map(y => y),
    'any': obj.any?.map(y => y),
    'method': obj.method,
    'not': obj.not?.map(y => y),
    'pathRegex': obj.pathRegex,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ResponseClass describes how to classify a response (e.g. success or failures).
 *
 * @schema ServiceProfileV1Alpha2SpecRoutesResponseClasses
 */
export interface ServiceProfileV1Alpha2SpecRoutesResponseClasses {
  /**
   * ResponseMatch describes the conditions under which to classify a response.
   *
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClasses#condition
   */
  readonly condition: ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClasses#isFailure
   */
  readonly isFailure?: boolean;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRoutesResponseClasses' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRoutesResponseClasses(obj: ServiceProfileV1Alpha2SpecRoutesResponseClasses | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'condition': toJson_ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition(obj.condition),
    'isFailure': obj.isFailure,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ResponseMatch describes the conditions under which to classify a response.
 *
 * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition
 */
export interface ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition {
  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition#all
   */
  readonly all?: any[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition#any
   */
  readonly any?: any[];

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition#not
   */
  readonly not?: any[];

  /**
   * Range describes a range of integers (e.g. status codes).
   *
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition#status
   */
  readonly status?: ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition(obj: ServiceProfileV1Alpha2SpecRoutesResponseClassesCondition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'all': obj.all?.map(y => y),
    'any': obj.any?.map(y => y),
    'not': obj.not?.map(y => y),
    'status': toJson_ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus(obj.status),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Range describes a range of integers (e.g. status codes).
 *
 * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus
 */
export interface ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus {
  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus#max
   */
  readonly max?: number;

  /**
   * @schema ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus#min
   */
  readonly min?: number;

}

/**
 * Converts an object of type 'ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus(obj: ServiceProfileV1Alpha2SpecRoutesResponseClassesConditionStatus | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'max': obj.max,
    'min': obj.min,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

