export { default as FlowChartAltFilled } from './lnif/Business/flow-chart-alt.svg?react';
export { default as InvestmentFilled } from './lnif/Business/investment.svg?react';
export { default as PieChartAltFilled } from './lnif/Business/pie-chart-alt.svg?react';
export { default as ChevronDownFilled } from './lnif/Direction/chevron-down.svg?react';
export { default as ChevronUpFilled } from './lnif/Direction/chevron-up.svg?react';
export { default as ExitFilled } from './lnif/Direction/exit.svg?react';
export { default as PencilFilled } from './lnif/Education/pencil.svg?react';
export { default as CheckmarkFilled } from './lnif/Interface and Sign/checkmark.svg?react';
export { default as CloseFilled } from './lnif/Interface and Sign/close.svg?react';
export { default as PlusFilled } from './lnif/Interface and Sign/plus.svg?react';
export { default as GraphAlt1Filled } from './lnif/Marketing/graph-alt-1.svg?react';
export { default as PieChartAlt1Filled } from './lnif/Marketing/pie-chart-alt-1.svg?react';
export { default as FriendsFilled } from './lnif/User/friends.svg?react';
export { default as UserAlt3Filled } from './lnif/User/user-alt-3.svg?react';
export { default as SparklesFilled } from './lnif/Weather/sparkles.svg?react';
export { default as CogFilled } from './lnif/Web and Technology/cog.svg?react';
export { default as FileExclamationFilled } from './lnif/Web and Technology/file-exclamation.svg?react';
export { default as StarFilled } from './lnif/Web and Technology/star.svg?react';
export { default as TapFilled } from './lnif/Web and Technology/tap.svg?react';
export { default as TrashCanFilled } from './lnif/Web and Technology/trash-can.svg?react';
export { default as UsersFilled } from './lnif/Web and Technology/users.svg?react';
